version: "3.7"

networks:
  wavdio-net:

services:

  wavdio-express:
    container_name: wavdio-express
    image: keepinmindbot/wavdio-express:3.0.1-test-15
    networks:
      - wavdio-net
    ports:
      - "3000:3000"
    depends_on:
      - wavdio-mongo

  wavdio-mongo:
    container_name: wavdio-mongo
    image: mongo:5-focal
    networks:
      - wavdio-net
    expose:
      - 27017
